name: Verify Code

on:
  workflow_dispatch: # This enables manual trigger via API or GitHub UI

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the code
      run: |
        python sig.py # Replace with the script you want to run
