
name: Verify Code

on:
  workflow_dispatch: # This enables the manual trigger of the workflow

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.0' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the code
      run: |
        python main.py # Replace with the script you want to run
